# https://cloud.google.com/appengine/docs/the-appengine-environments#comparing_high-level_features
# https://cloud.google.com/appengine/docs/standard

runtime: java17
instance_class: F2

network:
  session_affinity: false

vpc_access_connector:
  name: projects/sopra-fs24-group-07-server/locations/europe-west6/connectors/db-connector
#  egress-setting: all-traffic

# env variables (psw) will be added in pipeline
env_variables:
  PUSHER_APP_ID=1787826
  # ...
