name: Test Pull Request - dev GCP

on:
  pull_request:
    branches:
      - main

  # run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
           distribution: 'temurin'
           java-version: '17'

      - name: Set database password to dev GCP
        run: echo "dbPassword=${{ secrets.DB_PASSWORD_DEV }}" > dbpassword.properties

      - name: Set database URL to dev GCP
        run: echo "dbUrl=${{ secrets.DB_URL_DEV }}" > dburl.properties

      - name: Test and analyze with dev GCP
        run: ./gradlew test jacocoTestReport sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SPRING_PROFILES_ACTIVE: devGCP
          GRADLE_OPTS: '-DdbPassword=${{ secrets.DB_PASSWORD_DEV }} -DdbUrl=${{ secrets.DB_URL_DEV }}'

      - name: Build with Gradle
        run: ./gradlew build
#
#      - name: Test with Gradle
#        run: ./gradlew test
