name: UnitTests and Build

on:
  pull_request:
    branches:
      - main
  push:

  # run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
           distribution: 'temurin'
           java-version: '17'

      - name: Set up Spring Boot Database URL
        run: echo "SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/test_db" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew build
        env:
          SPRING_PROFILES_ACTIVE: dev
          DB_URL: jdbc:postgresql://localhost:5432/test_db
          DB_UNM: postgres
          DB_PSW: test_password
          DB_DDL_AUTO: create-drop

      - name: Test with Gradle and devRun profile
        run: ./gradlew test
        env:
          SPRING_PROFILES_ACTIVE: devRun
          DB_URL: jdbc:postgresql://localhost:5432/test_db
          DB_UNM: postgres
          DB_PSW: test_password
          DB_DDL_AUTO: create-drop
          PUSHER_APP_ID: 1787826
          PUSHER_KEY: ${{ secrets.PUSHER_KEY }}
          PUSHER_SECRET: ${{ secrets.PUSHER_SECRET }}
          AGORA_APP_ID: ${{ secrets.AGORA_APP_ID }}
          AGORA_APP_CERTIFICATE: ${{ secrets.AGORA_APP_CERTIFICATE }}

      - name: Test DB like prod profile
        run: |
          echo "spring.datasource.url=jdbc:postgresql://localhost:5432/test_db" >> src/main/resources/application.properties
          echo "spring.datasource.password=test_password" >> src/main/resources/application.properties
          cat src/main/resources/application.properties
          ./gradlew test --tests *Repository* --tests *ServiceIntegration*
        env:
          DB_UNM: postgres
          DB_DDL_AUTO: create-drop
          PUSHER_APP_ID: 1787826
          PUSHER_KEY: ${{ secrets.PUSHER_KEY }}
          PUSHER_SECRET: ${{ secrets.PUSHER_SECRET }}
          AGORA_APP_ID: ${{ secrets.AGORA_APP_ID }}
          AGORA_APP_CERTIFICATE: ${{ secrets.AGORA_APP_CERTIFICATE }}
