name: UnitTests and Build

on:
  pull_request:
    branches:
      - main
  push:

  # run the workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Install Java 17
        uses: actions/setup-java@v3
        with:
           distribution: 'temurin'
           java-version: '17'

      - name: Set up Spring Boot Database URL
        run: echo "SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/test_db" >> $GITHUB_ENV

      - name: Build with Gradle
        run: ./gradlew build
        env:
          dbUrl: jdbc:postgresql://localhost:5432/test_db
          dbPassword: test_password
#          DB_UNM: test_user
#          DB_DDL_AUTO: create


      - name: Test with Gradle
        run: ./gradlew test
        env:
          dbUrl: jdbc:postgresql://localhost:5432/test_db
          dbPassword: test_password
#          DB_UNM: test_user
#          DB_DDL_AUTO: create
